baseURL = "https://tarasa24.dev/"
locale = "en-us"
title = "Portfolio"

defaultContentLanguage = "en"

[params]
  cf_turnstile_site_key = "0x4AAAAAACCVl6oKRzbxrXlw"
  contact_worker_url = "https://portfolio-contact-form.tarasa24.workers.dev/"

[languages]
  [languages.en]
    weight = 1
    label = "English"
    locale = "en"
    contentDir = "content/en"
  [languages.cs]
    weight = 2
    label = "Čeština"
    locale = "cs"
    contentDir = "content/cs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true